using System.IO;
using UnityEditor;
using UnityEngine;
namespace SurvivalFP.EditorTools
{
    // Builds "SurvivalFP/PSX Lit" from the installed URP Lit shader, so it always matches the URP
    // version (Forward+, SSAO, shadows, GPU Resident Drawer). The only changes: vertex snapping in the
    // forward, depth and depth-normals passes, and procedural grime in the lit surface.
    // Rerun after upgrading URP: Survival FP > Rendering > Regenerate PSX Lit Shader.
    public static class PsxLitShaderGenerator
    {
        const string OutputFolder = "Assets/Game/Shaders/Generated";
        const string UrpShaders = "Packages/com.unity.render-pipelines.universal/Shaders";

        [MenuItem("Survival FP/Rendering/Regenerate PSX Lit Shader")]
        public static void Generate()
        {
            var package = UnityEditor.PackageManager.PackageInfo.FindForAssetPath(UrpShaders + "/Lit.shader");
            string root = package != null ? Path.Combine(package.resolvedPath, "Shaders") : Path.GetFullPath(UrpShaders);
            string lit = File.ReadAllText(Path.Combine(root, "Lit.shader")).Replace("\r\n", "\n");
            string input = File.ReadAllText(Path.Combine(root, "LitInput.hlsl")).Replace("\r\n", "\n");
            Directory.CreateDirectory(OutputFolder);

            // Lit surface: keep URP's include guard so the stock LitInput is skipped, add the grime amount
            // to the per-material constant buffer and apply grime at the end of surface initialisation.
            input = Require(input, "#include \"Packages/com.unity.render-pipelines.universal/Shaders/Utils/SurfaceType.hlsl\"",
                "#include \"Packages/com.unity.render-pipelines.universal/Shaders/Utils/SurfaceType.hlsl\"\n#include \"Assets/Game/Shaders/PsxLitCommon.hlsl\"");
            input = Require(input, "UNITY_TEXTURE_STREAMING_DEBUG_VARS;\nCBUFFER_END", "half _PsxGrime;\nUNITY_TEXTURE_STREAMING_DEBUG_VARS;\nCBUFFER_END");
            int init = input.IndexOf("inline void InitializeStandardLitSurfaceData");
            int end = input.LastIndexOf("}", input.LastIndexOf("#endif"));
            if (init < 0 || end < init) throw new System.InvalidOperationException("URP LitInput.hlsl layout changed: InitializeStandardLitSurfaceData not found.");
            input = input.Substring(0, end) + "    PsxApplyGrime(outSurfaceData, _PsxGrime);\n" + input.Substring(end);
            File.WriteAllText(Path.Combine(OutputFolder, "PsxLitInput.hlsl"), "// GENERATED by PsxLitShaderGenerator from URP LitInput.hlsl. Do not edit.\n" + input);

            lit = Require(lit, "Shader \"Universal Render Pipeline/Lit\"", "Shader \"SurvivalFP/PSX Lit\"");
            lit = Require(lit, "    Properties\n    {\n", "    Properties\n    {\n        [Header(PSX)] _PsxGrime(\"Grime\", Range(0, 1)) = 0.35\n");
            lit = lit.Replace("\"Packages/com.unity.render-pipelines.universal/Shaders/LitInput.hlsl\"", "\"" + OutputFolder + "/PsxLitInput.hlsl\"");
            lit = Wrap(lit, "LitForwardPass.hlsl", "PSX_FORWARD_PASS");
            lit = Wrap(lit, "DepthOnlyPass.hlsl", "PSX_DEPTH_ONLY_PASS");
            lit = Wrap(lit, "LitDepthNormalsPass.hlsl", "PSX_DEPTH_NORMALS_PASS");
            lit = Require(lit, "#pragma vertex LitPassVertex", "#pragma vertex PsxLitPassVertex");
            lit = Require(lit, "#pragma fragment LitPassFragment", "#pragma fragment PsxLitPassFragment");
            lit = Require(lit, "#pragma vertex DepthOnlyVertex", "#pragma vertex PsxDepthOnlyVertex");
            lit = Require(lit, "#pragma vertex DepthNormalsVertex", "#pragma vertex PsxDepthNormalsVertex");
            File.WriteAllText(Path.Combine(OutputFolder, "PsxLit.shader"), "// GENERATED by PsxLitShaderGenerator from URP " + (package != null ? package.version : "") + " Lit.shader. Do not edit.\n" + lit);
            AssetDatabase.Refresh();
            Debug.Log("PSX Lit shader generated in " + OutputFolder);
        }

        static string Wrap(string shader, string passFile, string define)
        {
            string include = "#include \"Packages/com.unity.render-pipelines.universal/Shaders/" + passFile + "\"";
            return Require(shader, include, "#define " + define + "\n            " + include + "\n            #include \"Assets/Game/Shaders/PsxLitWrappers.hlsl\"");
        }

        static string Require(string text, string find, string replace)
        {
            if (!text.Contains(find)) throw new System.InvalidOperationException("URP shader layout changed: '" + find + "' not found.");
            return text.Replace(find, replace);
        }
    }
}
